Attribute VB_Name = "Module1"
Public PrmPath As String

Public strAnalog_ As String
Public strDeviceType As String
Public bDeletePinLib As Boolean
Public bDeleteConnect As Boolean
Public intBomGeShu As Integer
Public strVerName_1 As String
Public strVerName_2 As String
Public strVerName_3 As String
Public strVerName_4 As String
Public strVerName_5 As String
Public strVerName_6 As String
Public strVerName_7 As String
Public strVerName_8 As String
Public intYY As Integer
Public strOutFileName As String
Public strFileNameOpen As String
